version: '3.8'

services:
  postgres:
    image: postgres:15beta3
    container_name: PostgreSQL
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - /home/ubuntu/shopping-cart/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/create_schema.sql

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - "8080:8080"

  shoppingCart:
    image: shopping_cart
    container_name: shoppingCart
    ports:
      - "80:80"
    depends_on:
      - postgres
      - adminer
